&defaults_config

global:
  environment: RMS_sandbox

  test_types: [browser] # api, browser, mobile_app

  request_logging: true
  try_with_logging: true
  logging_severity: info

<%= IO.read(filename) if File.exists?(filename) %>
